# Generated by Django 2.2.7 on 2019-12-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
