# Generated by Django 3.0 on 2019-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('capital', models.CharField(max_length=64)),
                ('population', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=128)),
                ('continent', models.CharField(max_length=32)),
                ('flag', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
