# Generated by Django 2.2.7 on 2019-12-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('team', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('link', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('height', models.CharField(max_length=32)),
                ('weight', models.CharField(max_length=32)),
                ('born', models.CharField(max_length=32)),
                ('age', models.CharField(max_length=16)),
                ('years_in_nba', models.CharField(max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'player',
                'ordering': ('-created',),
            },
        ),
    ]
